version: "3.8"
services:
  couchdb:
    image: couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    ports:
      - "5984:5984"
    volumes:
      - ./dockerConfig/couchDB/configs:/opt/couchdb/etc/default.d/
      - ./dockerData/couchDB:/opt/couchdb/data
